// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'is__active': string;
  'logo': string;
  'nav': string;
  'navLink': string;
  'root': string;
  'wrapper': string;
}
export const cssExports: CssExports;
export default cssExports;
