// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'error': string;
  'errorHeader': string;
  'headerWrapper': string;
  'img': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
